// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sanction/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	WatchThreshold             uint32                 `protobuf:"varint,1,opt,name=watch_threshold,json=watchThreshold,proto3" json:"watch_threshold,omitempty"`
	BlockThreshold             uint32                 `protobuf:"varint,2,opt,name=block_threshold,json=blockThreshold,proto3" json:"block_threshold,omitempty"`
	FreezeThreshold            uint32                 `protobuf:"varint,3,opt,name=freeze_threshold,json=freezeThreshold,proto3" json:"freeze_threshold,omitempty"`
	RevertThreshold            uint32                 `protobuf:"varint,4,opt,name=revert_threshold,json=revertThreshold,proto3" json:"revert_threshold,omitempty"`
	QuorumThreshold            uint32                 `protobuf:"varint,5,opt,name=quorum_threshold,json=quorumThreshold,proto3" json:"quorum_threshold,omitempty"`
	UnanimousRequiredForRevert bool                   `protobuf:"varint,6,opt,name=unanimous_required_for_revert,json=unanimousRequiredForRevert,proto3" json:"unanimous_required_for_revert,omitempty"`
	EvidenceTtlBlocks          uint64                 `protobuf:"varint,7,opt,name=evidence_ttl_blocks,json=evidenceTtlBlocks,proto3" json:"evidence_ttl_blocks,omitempty"`
	VotingPeriodBlocks         uint64                 `protobuf:"varint,8,opt,name=voting_period_blocks,json=votingPeriodBlocks,proto3" json:"voting_period_blocks,omitempty"`
	AcceptedRiskSources        []string               `protobuf:"bytes,9,rep,name=accepted_risk_sources,json=acceptedRiskSources,proto3" json:"accepted_risk_sources,omitempty"`
	HighRiskCategories         []string               `protobuf:"bytes,10,rep,name=high_risk_categories,json=highRiskCategories,proto3" json:"high_risk_categories,omitempty"`
	AllowedActions             []SanctionAction       `protobuf:"varint,11,rep,packed,name=allowed_actions,json=allowedActions,proto3,enum=sanction.v1.SanctionAction" json:"allowed_actions,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_sanction_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_sanction_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetWatchThreshold() uint32 {
	if x != nil {
		return x.WatchThreshold
	}
	return 0
}

func (x *Params) GetBlockThreshold() uint32 {
	if x != nil {
		return x.BlockThreshold
	}
	return 0
}

func (x *Params) GetFreezeThreshold() uint32 {
	if x != nil {
		return x.FreezeThreshold
	}
	return 0
}

func (x *Params) GetRevertThreshold() uint32 {
	if x != nil {
		return x.RevertThreshold
	}
	return 0
}

func (x *Params) GetQuorumThreshold() uint32 {
	if x != nil {
		return x.QuorumThreshold
	}
	return 0
}

func (x *Params) GetUnanimousRequiredForRevert() bool {
	if x != nil {
		return x.UnanimousRequiredForRevert
	}
	return false
}

func (x *Params) GetEvidenceTtlBlocks() uint64 {
	if x != nil {
		return x.EvidenceTtlBlocks
	}
	return 0
}

func (x *Params) GetVotingPeriodBlocks() uint64 {
	if x != nil {
		return x.VotingPeriodBlocks
	}
	return 0
}

func (x *Params) GetAcceptedRiskSources() []string {
	if x != nil {
		return x.AcceptedRiskSources
	}
	return nil
}

func (x *Params) GetHighRiskCategories() []string {
	if x != nil {
		return x.HighRiskCategories
	}
	return nil
}

func (x *Params) GetAllowedActions() []SanctionAction {
	if x != nil {
		return x.AllowedActions
	}
	return nil
}

type GenesisState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Params           *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Agents           []*AgentInfo           `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	RiskReports      []*RiskReport          `protobuf:"bytes,3,rep,name=risk_reports,json=riskReports,proto3" json:"risk_reports,omitempty"`
	SanctionCases    []*SanctionCase        `protobuf:"bytes,4,rep,name=sanction_cases,json=sanctionCases,proto3" json:"sanction_cases,omitempty"`
	SanctionVotes    []*SanctionVote        `protobuf:"bytes,5,rep,name=sanction_votes,json=sanctionVotes,proto3" json:"sanction_votes,omitempty"`
	ActiveSanctions  []*ActiveSanction      `protobuf:"bytes,6,rep,name=active_sanctions,json=activeSanctions,proto3" json:"active_sanctions,omitempty"`
	FrozenAddresses  []*FreezeRecord        `protobuf:"bytes,7,rep,name=frozen_addresses,json=frozenAddresses,proto3" json:"frozen_addresses,omitempty"`
	ExecutionRecords []*ExecutionRecord     `protobuf:"bytes,8,rep,name=execution_records,json=executionRecords,proto3" json:"execution_records,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_sanction_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_sanction_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GenesisState) GetRiskReports() []*RiskReport {
	if x != nil {
		return x.RiskReports
	}
	return nil
}

func (x *GenesisState) GetSanctionCases() []*SanctionCase {
	if x != nil {
		return x.SanctionCases
	}
	return nil
}

func (x *GenesisState) GetSanctionVotes() []*SanctionVote {
	if x != nil {
		return x.SanctionVotes
	}
	return nil
}

func (x *GenesisState) GetActiveSanctions() []*ActiveSanction {
	if x != nil {
		return x.ActiveSanctions
	}
	return nil
}

func (x *GenesisState) GetFrozenAddresses() []*FreezeRecord {
	if x != nil {
		return x.FrozenAddresses
	}
	return nil
}

func (x *GenesisState) GetExecutionRecords() []*ExecutionRecord {
	if x != nil {
		return x.ExecutionRecords
	}
	return nil
}

var File_sanction_v1_genesis_proto protoreflect.FileDescriptor

const file_sanction_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"\x19sanction/v1/genesis.proto\x12\vsanction.v1\x1a\x14gogoproto/gogo.proto\x1a\x17sanction/v1/types.proto\"\xac\x04\n" +
	"\x06Params\x12'\n" +
	"\x0fwatch_threshold\x18\x01 \x01(\rR\x0ewatchThreshold\x12'\n" +
	"\x0fblock_threshold\x18\x02 \x01(\rR\x0eblockThreshold\x12)\n" +
	"\x10freeze_threshold\x18\x03 \x01(\rR\x0ffreezeThreshold\x12)\n" +
	"\x10revert_threshold\x18\x04 \x01(\rR\x0frevertThreshold\x12)\n" +
	"\x10quorum_threshold\x18\x05 \x01(\rR\x0fquorumThreshold\x12A\n" +
	"\x1dunanimous_required_for_revert\x18\x06 \x01(\bR\x1aunanimousRequiredForRevert\x12.\n" +
	"\x13evidence_ttl_blocks\x18\a \x01(\x04R\x11evidenceTtlBlocks\x120\n" +
	"\x14voting_period_blocks\x18\b \x01(\x04R\x12votingPeriodBlocks\x122\n" +
	"\x15accepted_risk_sources\x18\t \x03(\tR\x13acceptedRiskSources\x120\n" +
	"\x14high_risk_categories\x18\n" +
	" \x03(\tR\x12highRiskCategories\x12D\n" +
	"\x0fallowed_actions\x18\v \x03(\x0e2\x1b.sanction.v1.SanctionActionR\x0eallowedActions\"\xb4\x04\n" +
	"\fGenesisState\x121\n" +
	"\x06params\x18\x01 \x01(\v2\x13.sanction.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x124\n" +
	"\x06agents\x18\x02 \x03(\v2\x16.sanction.v1.AgentInfoB\x04\xc8\xde\x1f\x00R\x06agents\x12@\n" +
	"\frisk_reports\x18\x03 \x03(\v2\x17.sanction.v1.RiskReportB\x04\xc8\xde\x1f\x00R\vriskReports\x12F\n" +
	"\x0esanction_cases\x18\x04 \x03(\v2\x19.sanction.v1.SanctionCaseB\x04\xc8\xde\x1f\x00R\rsanctionCases\x12F\n" +
	"\x0esanction_votes\x18\x05 \x03(\v2\x19.sanction.v1.SanctionVoteB\x04\xc8\xde\x1f\x00R\rsanctionVotes\x12L\n" +
	"\x10active_sanctions\x18\x06 \x03(\v2\x1b.sanction.v1.ActiveSanctionB\x04\xc8\xde\x1f\x00R\x0factiveSanctions\x12J\n" +
	"\x10frozen_addresses\x18\a \x03(\v2\x19.sanction.v1.FreezeRecordB\x04\xc8\xde\x1f\x00R\x0ffrozenAddresses\x12O\n" +
	"\x11execution_records\x18\b \x03(\v2\x1c.sanction.v1.ExecutionRecordB\x04\xc8\xde\x1f\x00R\x10executionRecordsB5Z3github.com/crossref/crossref-chain/x/sanction/typesb\x06proto3"

var (
	file_sanction_v1_genesis_proto_rawDescOnce sync.Once
	file_sanction_v1_genesis_proto_rawDescData []byte
)

func file_sanction_v1_genesis_proto_rawDescGZIP() []byte {
	file_sanction_v1_genesis_proto_rawDescOnce.Do(func() {
		file_sanction_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sanction_v1_genesis_proto_rawDesc), len(file_sanction_v1_genesis_proto_rawDesc)))
	})
	return file_sanction_v1_genesis_proto_rawDescData
}

var file_sanction_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sanction_v1_genesis_proto_goTypes = []any{
	(*Params)(nil),          // 0: sanction.v1.Params
	(*GenesisState)(nil),    // 1: sanction.v1.GenesisState
	(SanctionAction)(0),     // 2: sanction.v1.SanctionAction
	(*AgentInfo)(nil),       // 3: sanction.v1.AgentInfo
	(*RiskReport)(nil),      // 4: sanction.v1.RiskReport
	(*SanctionCase)(nil),    // 5: sanction.v1.SanctionCase
	(*SanctionVote)(nil),    // 6: sanction.v1.SanctionVote
	(*ActiveSanction)(nil),  // 7: sanction.v1.ActiveSanction
	(*FreezeRecord)(nil),    // 8: sanction.v1.FreezeRecord
	(*ExecutionRecord)(nil), // 9: sanction.v1.ExecutionRecord
}
var file_sanction_v1_genesis_proto_depIdxs = []int32{
	2, // 0: sanction.v1.Params.allowed_actions:type_name -> sanction.v1.SanctionAction
	0, // 1: sanction.v1.GenesisState.params:type_name -> sanction.v1.Params
	3, // 2: sanction.v1.GenesisState.agents:type_name -> sanction.v1.AgentInfo
	4, // 3: sanction.v1.GenesisState.risk_reports:type_name -> sanction.v1.RiskReport
	5, // 4: sanction.v1.GenesisState.sanction_cases:type_name -> sanction.v1.SanctionCase
	6, // 5: sanction.v1.GenesisState.sanction_votes:type_name -> sanction.v1.SanctionVote
	7, // 6: sanction.v1.GenesisState.active_sanctions:type_name -> sanction.v1.ActiveSanction
	8, // 7: sanction.v1.GenesisState.frozen_addresses:type_name -> sanction.v1.FreezeRecord
	9, // 8: sanction.v1.GenesisState.execution_records:type_name -> sanction.v1.ExecutionRecord
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sanction_v1_genesis_proto_init() }
func file_sanction_v1_genesis_proto_init() {
	if File_sanction_v1_genesis_proto != nil {
		return
	}
	file_sanction_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sanction_v1_genesis_proto_rawDesc), len(file_sanction_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sanction_v1_genesis_proto_goTypes,
		DependencyIndexes: file_sanction_v1_genesis_proto_depIdxs,
		MessageInfos:      file_sanction_v1_genesis_proto_msgTypes,
	}.Build()
	File_sanction_v1_genesis_proto = out.File
	file_sanction_v1_genesis_proto_goTypes = nil
	file_sanction_v1_genesis_proto_depIdxs = nil
}
