// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sanction/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAgentRequest) Reset() {
	*x = QueryAgentRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentRequest) ProtoMessage() {}

func (x *QueryAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentRequest.ProtoReflect.Descriptor instead.
func (*QueryAgentRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type QueryAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAgentResponse) Reset() {
	*x = QueryAgentResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentResponse) ProtoMessage() {}

func (x *QueryAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentResponse.ProtoReflect.Descriptor instead.
func (*QueryAgentResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type QueryAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAgentsRequest) Reset() {
	*x = QueryAgentsRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentsRequest) ProtoMessage() {}

func (x *QueryAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentsRequest.ProtoReflect.Descriptor instead.
func (*QueryAgentsRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{4}
}

type QueryAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAgentsResponse) Reset() {
	*x = QueryAgentsResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentsResponse) ProtoMessage() {}

func (x *QueryAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentsResponse.ProtoReflect.Descriptor instead.
func (*QueryAgentsResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type QueryRiskReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRiskReportRequest) Reset() {
	*x = QueryRiskReportRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRiskReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRiskReportRequest) ProtoMessage() {}

func (x *QueryRiskReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRiskReportRequest.ProtoReflect.Descriptor instead.
func (*QueryRiskReportRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRiskReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type QueryRiskReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *RiskReport            `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRiskReportResponse) Reset() {
	*x = QueryRiskReportResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRiskReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRiskReportResponse) ProtoMessage() {}

func (x *QueryRiskReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRiskReportResponse.ProtoReflect.Descriptor instead.
func (*QueryRiskReportResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRiskReportResponse) GetReport() *RiskReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type QueryRiskReportsByTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRiskReportsByTxRequest) Reset() {
	*x = QueryRiskReportsByTxRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRiskReportsByTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRiskReportsByTxRequest) ProtoMessage() {}

func (x *QueryRiskReportsByTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRiskReportsByTxRequest.ProtoReflect.Descriptor instead.
func (*QueryRiskReportsByTxRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRiskReportsByTxRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type QueryRiskReportsByTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*RiskReport          `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRiskReportsByTxResponse) Reset() {
	*x = QueryRiskReportsByTxResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRiskReportsByTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRiskReportsByTxResponse) ProtoMessage() {}

func (x *QueryRiskReportsByTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRiskReportsByTxResponse.ProtoReflect.Descriptor instead.
func (*QueryRiskReportsByTxResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRiskReportsByTxResponse) GetReports() []*RiskReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type QuerySanctionCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySanctionCaseRequest) Reset() {
	*x = QuerySanctionCaseRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySanctionCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySanctionCaseRequest) ProtoMessage() {}

func (x *QuerySanctionCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySanctionCaseRequest.ProtoReflect.Descriptor instead.
func (*QuerySanctionCaseRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QuerySanctionCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type QuerySanctionCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SanctionCase  *SanctionCase          `protobuf:"bytes,1,opt,name=sanction_case,json=sanctionCase,proto3" json:"sanction_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySanctionCaseResponse) Reset() {
	*x = QuerySanctionCaseResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySanctionCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySanctionCaseResponse) ProtoMessage() {}

func (x *QuerySanctionCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySanctionCaseResponse.ProtoReflect.Descriptor instead.
func (*QuerySanctionCaseResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QuerySanctionCaseResponse) GetSanctionCase() *SanctionCase {
	if x != nil {
		return x.SanctionCase
	}
	return nil
}

type QuerySanctionCasesByTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySanctionCasesByTxRequest) Reset() {
	*x = QuerySanctionCasesByTxRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySanctionCasesByTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySanctionCasesByTxRequest) ProtoMessage() {}

func (x *QuerySanctionCasesByTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySanctionCasesByTxRequest.ProtoReflect.Descriptor instead.
func (*QuerySanctionCasesByTxRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QuerySanctionCasesByTxRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type QuerySanctionCasesByTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SanctionCases []*SanctionCase        `protobuf:"bytes,1,rep,name=sanction_cases,json=sanctionCases,proto3" json:"sanction_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySanctionCasesByTxResponse) Reset() {
	*x = QuerySanctionCasesByTxResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySanctionCasesByTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySanctionCasesByTxResponse) ProtoMessage() {}

func (x *QuerySanctionCasesByTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySanctionCasesByTxResponse.ProtoReflect.Descriptor instead.
func (*QuerySanctionCasesByTxResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QuerySanctionCasesByTxResponse) GetSanctionCases() []*SanctionCase {
	if x != nil {
		return x.SanctionCases
	}
	return nil
}

type QuerySanctionVotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySanctionVotesRequest) Reset() {
	*x = QuerySanctionVotesRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySanctionVotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySanctionVotesRequest) ProtoMessage() {}

func (x *QuerySanctionVotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySanctionVotesRequest.ProtoReflect.Descriptor instead.
func (*QuerySanctionVotesRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QuerySanctionVotesRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type QuerySanctionVotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Votes         []*SanctionVote        `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySanctionVotesResponse) Reset() {
	*x = QuerySanctionVotesResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySanctionVotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySanctionVotesResponse) ProtoMessage() {}

func (x *QuerySanctionVotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySanctionVotesResponse.ProtoReflect.Descriptor instead.
func (*QuerySanctionVotesResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QuerySanctionVotesResponse) GetVotes() []*SanctionVote {
	if x != nil {
		return x.Votes
	}
	return nil
}

type QueryActiveTxSanctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActiveTxSanctionRequest) Reset() {
	*x = QueryActiveTxSanctionRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActiveTxSanctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveTxSanctionRequest) ProtoMessage() {}

func (x *QueryActiveTxSanctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveTxSanctionRequest.ProtoReflect.Descriptor instead.
func (*QueryActiveTxSanctionRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryActiveTxSanctionRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type QueryActiveTxSanctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sanction      *ActiveSanction        `protobuf:"bytes,1,opt,name=sanction,proto3" json:"sanction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActiveTxSanctionResponse) Reset() {
	*x = QueryActiveTxSanctionResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActiveTxSanctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveTxSanctionResponse) ProtoMessage() {}

func (x *QueryActiveTxSanctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveTxSanctionResponse.ProtoReflect.Descriptor instead.
func (*QueryActiveTxSanctionResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryActiveTxSanctionResponse) GetSanction() *ActiveSanction {
	if x != nil {
		return x.Sanction
	}
	return nil
}

type QueryFrozenAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFrozenAddressRequest) Reset() {
	*x = QueryFrozenAddressRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFrozenAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFrozenAddressRequest) ProtoMessage() {}

func (x *QueryFrozenAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFrozenAddressRequest.ProtoReflect.Descriptor instead.
func (*QueryFrozenAddressRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{18}
}

func (x *QueryFrozenAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type QueryFrozenAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Freeze        *FreezeRecord          `protobuf:"bytes,1,opt,name=freeze,proto3" json:"freeze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFrozenAddressResponse) Reset() {
	*x = QueryFrozenAddressResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFrozenAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFrozenAddressResponse) ProtoMessage() {}

func (x *QueryFrozenAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFrozenAddressResponse.ProtoReflect.Descriptor instead.
func (*QueryFrozenAddressResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryFrozenAddressResponse) GetFreeze() *FreezeRecord {
	if x != nil {
		return x.Freeze
	}
	return nil
}

type QueryExecutionRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExecutionRecordRequest) Reset() {
	*x = QueryExecutionRecordRequest{}
	mi := &file_sanction_v1_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecutionRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecutionRecordRequest) ProtoMessage() {}

func (x *QueryExecutionRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecutionRecordRequest.ProtoReflect.Descriptor instead.
func (*QueryExecutionRecordRequest) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{20}
}

func (x *QueryExecutionRecordRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type QueryExecutionRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExecutionRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExecutionRecordResponse) Reset() {
	*x = QueryExecutionRecordResponse{}
	mi := &file_sanction_v1_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecutionRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecutionRecordResponse) ProtoMessage() {}

func (x *QueryExecutionRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecutionRecordResponse.ProtoReflect.Descriptor instead.
func (*QueryExecutionRecordResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_query_proto_rawDescGZIP(), []int{21}
}

func (x *QueryExecutionRecordResponse) GetRecord() *ExecutionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_sanction_v1_query_proto protoreflect.FileDescriptor

const file_sanction_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x17sanction/v1/query.proto\x12\vsanction.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19sanction/v1/genesis.proto\x1a\x17sanction/v1/types.proto\"\x14\n" +
	"\x12QueryParamsRequest\"B\n" +
	"\x13QueryParamsResponse\x12+\n" +
	"\x06params\x18\x01 \x01(\v2\x13.sanction.v1.ParamsR\x06params\".\n" +
	"\x11QueryAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"B\n" +
	"\x12QueryAgentResponse\x12,\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.sanction.v1.AgentInfoR\x05agent\"\x14\n" +
	"\x12QueryAgentsRequest\"E\n" +
	"\x13QueryAgentsResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.sanction.v1.AgentInfoR\x06agents\"5\n" +
	"\x16QueryRiskReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"J\n" +
	"\x17QueryRiskReportResponse\x12/\n" +
	"\x06report\x18\x01 \x01(\v2\x17.sanction.v1.RiskReportR\x06report\"6\n" +
	"\x1bQueryRiskReportsByTxRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"Q\n" +
	"\x1cQueryRiskReportsByTxResponse\x121\n" +
	"\areports\x18\x01 \x03(\v2\x17.sanction.v1.RiskReportR\areports\"3\n" +
	"\x18QuerySanctionCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"[\n" +
	"\x19QuerySanctionCaseResponse\x12>\n" +
	"\rsanction_case\x18\x01 \x01(\v2\x19.sanction.v1.SanctionCaseR\fsanctionCase\"8\n" +
	"\x1dQuerySanctionCasesByTxRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"b\n" +
	"\x1eQuerySanctionCasesByTxResponse\x12@\n" +
	"\x0esanction_cases\x18\x01 \x03(\v2\x19.sanction.v1.SanctionCaseR\rsanctionCases\"4\n" +
	"\x19QuerySanctionVotesRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"M\n" +
	"\x1aQuerySanctionVotesResponse\x12/\n" +
	"\x05votes\x18\x01 \x03(\v2\x19.sanction.v1.SanctionVoteR\x05votes\"7\n" +
	"\x1cQueryActiveTxSanctionRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"X\n" +
	"\x1dQueryActiveTxSanctionResponse\x127\n" +
	"\bsanction\x18\x01 \x01(\v2\x1b.sanction.v1.ActiveSanctionR\bsanction\"5\n" +
	"\x19QueryFrozenAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"O\n" +
	"\x1aQueryFrozenAddressResponse\x121\n" +
	"\x06freeze\x18\x01 \x01(\v2\x19.sanction.v1.FreezeRecordR\x06freeze\"6\n" +
	"\x1bQueryExecutionRecordRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"T\n" +
	"\x1cQueryExecutionRecordResponse\x124\n" +
	"\x06record\x18\x01 \x01(\v2\x1c.sanction.v1.ExecutionRecordR\x06record2\xd0\v\n" +
	"\x05Query\x12h\n" +
	"\x06Params\x12\x1f.sanction.v1.QueryParamsRequest\x1a .sanction.v1.QueryParamsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/sanction/v1/params\x12p\n" +
	"\x05Agent\x12\x1e.sanction.v1.QueryAgentRequest\x1a\x1f.sanction.v1.QueryAgentResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/sanction/v1/agents/{agent_id}\x12h\n" +
	"\x06Agents\x12\x1f.sanction.v1.QueryAgentsRequest\x1a .sanction.v1.QueryAgentsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/sanction/v1/agents\x12\x86\x01\n" +
	"\n" +
	"RiskReport\x12#.sanction.v1.QueryRiskReportRequest\x1a$.sanction.v1.QueryRiskReportResponse\"-\x82\xd3\xe4\x93\x02'\x12%/sanction/v1/risk_reports/{report_id}\x12\x96\x01\n" +
	"\x0fRiskReportsByTx\x12(.sanction.v1.QueryRiskReportsByTxRequest\x1a).sanction.v1.QueryRiskReportsByTxResponse\".\x82\xd3\xe4\x93\x02(\x12&/sanction/v1/tx/{tx_hash}/risk_reports\x12\x83\x01\n" +
	"\fSanctionCase\x12%.sanction.v1.QuerySanctionCaseRequest\x1a&.sanction.v1.QuerySanctionCaseResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/sanction/v1/cases/{case_id}\x12\x95\x01\n" +
	"\x11SanctionCasesByTx\x12*.sanction.v1.QuerySanctionCasesByTxRequest\x1a+.sanction.v1.QuerySanctionCasesByTxResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/sanction/v1/tx/{tx_hash}/cases\x12\x8c\x01\n" +
	"\rSanctionVotes\x12&.sanction.v1.QuerySanctionVotesRequest\x1a'.sanction.v1.QuerySanctionVotesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/sanction/v1/cases/{case_id}/votes\x12\x93\x01\n" +
	"\x10ActiveTxSanction\x12).sanction.v1.QueryActiveTxSanctionRequest\x1a*.sanction.v1.QueryActiveTxSanctionResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /sanction/v1/tx/{tx_hash}/active\x12\x87\x01\n" +
	"\rFrozenAddress\x12&.sanction.v1.QueryFrozenAddressRequest\x1a'.sanction.v1.QueryFrozenAddressResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/sanction/v1/frozen/{address}\x12\x91\x01\n" +
	"\x0fExecutionRecord\x12(.sanction.v1.QueryExecutionRecordRequest\x1a).sanction.v1.QueryExecutionRecordResponse\")\x82\xd3\xe4\x93\x02#\x12!/sanction/v1/executions/{case_id}B5Z3github.com/crossref/crossref-chain/x/sanction/typesb\x06proto3"

var (
	file_sanction_v1_query_proto_rawDescOnce sync.Once
	file_sanction_v1_query_proto_rawDescData []byte
)

func file_sanction_v1_query_proto_rawDescGZIP() []byte {
	file_sanction_v1_query_proto_rawDescOnce.Do(func() {
		file_sanction_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sanction_v1_query_proto_rawDesc), len(file_sanction_v1_query_proto_rawDesc)))
	})
	return file_sanction_v1_query_proto_rawDescData
}

var file_sanction_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_sanction_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),             // 0: sanction.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),            // 1: sanction.v1.QueryParamsResponse
	(*QueryAgentRequest)(nil),              // 2: sanction.v1.QueryAgentRequest
	(*QueryAgentResponse)(nil),             // 3: sanction.v1.QueryAgentResponse
	(*QueryAgentsRequest)(nil),             // 4: sanction.v1.QueryAgentsRequest
	(*QueryAgentsResponse)(nil),            // 5: sanction.v1.QueryAgentsResponse
	(*QueryRiskReportRequest)(nil),         // 6: sanction.v1.QueryRiskReportRequest
	(*QueryRiskReportResponse)(nil),        // 7: sanction.v1.QueryRiskReportResponse
	(*QueryRiskReportsByTxRequest)(nil),    // 8: sanction.v1.QueryRiskReportsByTxRequest
	(*QueryRiskReportsByTxResponse)(nil),   // 9: sanction.v1.QueryRiskReportsByTxResponse
	(*QuerySanctionCaseRequest)(nil),       // 10: sanction.v1.QuerySanctionCaseRequest
	(*QuerySanctionCaseResponse)(nil),      // 11: sanction.v1.QuerySanctionCaseResponse
	(*QuerySanctionCasesByTxRequest)(nil),  // 12: sanction.v1.QuerySanctionCasesByTxRequest
	(*QuerySanctionCasesByTxResponse)(nil), // 13: sanction.v1.QuerySanctionCasesByTxResponse
	(*QuerySanctionVotesRequest)(nil),      // 14: sanction.v1.QuerySanctionVotesRequest
	(*QuerySanctionVotesResponse)(nil),     // 15: sanction.v1.QuerySanctionVotesResponse
	(*QueryActiveTxSanctionRequest)(nil),   // 16: sanction.v1.QueryActiveTxSanctionRequest
	(*QueryActiveTxSanctionResponse)(nil),  // 17: sanction.v1.QueryActiveTxSanctionResponse
	(*QueryFrozenAddressRequest)(nil),      // 18: sanction.v1.QueryFrozenAddressRequest
	(*QueryFrozenAddressResponse)(nil),     // 19: sanction.v1.QueryFrozenAddressResponse
	(*QueryExecutionRecordRequest)(nil),    // 20: sanction.v1.QueryExecutionRecordRequest
	(*QueryExecutionRecordResponse)(nil),   // 21: sanction.v1.QueryExecutionRecordResponse
	(*Params)(nil),                         // 22: sanction.v1.Params
	(*AgentInfo)(nil),                      // 23: sanction.v1.AgentInfo
	(*RiskReport)(nil),                     // 24: sanction.v1.RiskReport
	(*SanctionCase)(nil),                   // 25: sanction.v1.SanctionCase
	(*SanctionVote)(nil),                   // 26: sanction.v1.SanctionVote
	(*ActiveSanction)(nil),                 // 27: sanction.v1.ActiveSanction
	(*FreezeRecord)(nil),                   // 28: sanction.v1.FreezeRecord
	(*ExecutionRecord)(nil),                // 29: sanction.v1.ExecutionRecord
}
var file_sanction_v1_query_proto_depIdxs = []int32{
	22, // 0: sanction.v1.QueryParamsResponse.params:type_name -> sanction.v1.Params
	23, // 1: sanction.v1.QueryAgentResponse.agent:type_name -> sanction.v1.AgentInfo
	23, // 2: sanction.v1.QueryAgentsResponse.agents:type_name -> sanction.v1.AgentInfo
	24, // 3: sanction.v1.QueryRiskReportResponse.report:type_name -> sanction.v1.RiskReport
	24, // 4: sanction.v1.QueryRiskReportsByTxResponse.reports:type_name -> sanction.v1.RiskReport
	25, // 5: sanction.v1.QuerySanctionCaseResponse.sanction_case:type_name -> sanction.v1.SanctionCase
	25, // 6: sanction.v1.QuerySanctionCasesByTxResponse.sanction_cases:type_name -> sanction.v1.SanctionCase
	26, // 7: sanction.v1.QuerySanctionVotesResponse.votes:type_name -> sanction.v1.SanctionVote
	27, // 8: sanction.v1.QueryActiveTxSanctionResponse.sanction:type_name -> sanction.v1.ActiveSanction
	28, // 9: sanction.v1.QueryFrozenAddressResponse.freeze:type_name -> sanction.v1.FreezeRecord
	29, // 10: sanction.v1.QueryExecutionRecordResponse.record:type_name -> sanction.v1.ExecutionRecord
	0,  // 11: sanction.v1.Query.Params:input_type -> sanction.v1.QueryParamsRequest
	2,  // 12: sanction.v1.Query.Agent:input_type -> sanction.v1.QueryAgentRequest
	4,  // 13: sanction.v1.Query.Agents:input_type -> sanction.v1.QueryAgentsRequest
	6,  // 14: sanction.v1.Query.RiskReport:input_type -> sanction.v1.QueryRiskReportRequest
	8,  // 15: sanction.v1.Query.RiskReportsByTx:input_type -> sanction.v1.QueryRiskReportsByTxRequest
	10, // 16: sanction.v1.Query.SanctionCase:input_type -> sanction.v1.QuerySanctionCaseRequest
	12, // 17: sanction.v1.Query.SanctionCasesByTx:input_type -> sanction.v1.QuerySanctionCasesByTxRequest
	14, // 18: sanction.v1.Query.SanctionVotes:input_type -> sanction.v1.QuerySanctionVotesRequest
	16, // 19: sanction.v1.Query.ActiveTxSanction:input_type -> sanction.v1.QueryActiveTxSanctionRequest
	18, // 20: sanction.v1.Query.FrozenAddress:input_type -> sanction.v1.QueryFrozenAddressRequest
	20, // 21: sanction.v1.Query.ExecutionRecord:input_type -> sanction.v1.QueryExecutionRecordRequest
	1,  // 22: sanction.v1.Query.Params:output_type -> sanction.v1.QueryParamsResponse
	3,  // 23: sanction.v1.Query.Agent:output_type -> sanction.v1.QueryAgentResponse
	5,  // 24: sanction.v1.Query.Agents:output_type -> sanction.v1.QueryAgentsResponse
	7,  // 25: sanction.v1.Query.RiskReport:output_type -> sanction.v1.QueryRiskReportResponse
	9,  // 26: sanction.v1.Query.RiskReportsByTx:output_type -> sanction.v1.QueryRiskReportsByTxResponse
	11, // 27: sanction.v1.Query.SanctionCase:output_type -> sanction.v1.QuerySanctionCaseResponse
	13, // 28: sanction.v1.Query.SanctionCasesByTx:output_type -> sanction.v1.QuerySanctionCasesByTxResponse
	15, // 29: sanction.v1.Query.SanctionVotes:output_type -> sanction.v1.QuerySanctionVotesResponse
	17, // 30: sanction.v1.Query.ActiveTxSanction:output_type -> sanction.v1.QueryActiveTxSanctionResponse
	19, // 31: sanction.v1.Query.FrozenAddress:output_type -> sanction.v1.QueryFrozenAddressResponse
	21, // 32: sanction.v1.Query.ExecutionRecord:output_type -> sanction.v1.QueryExecutionRecordResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sanction_v1_query_proto_init() }
func file_sanction_v1_query_proto_init() {
	if File_sanction_v1_query_proto != nil {
		return
	}
	file_sanction_v1_genesis_proto_init()
	file_sanction_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sanction_v1_query_proto_rawDesc), len(file_sanction_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sanction_v1_query_proto_goTypes,
		DependencyIndexes: file_sanction_v1_query_proto_depIdxs,
		MessageInfos:      file_sanction_v1_query_proto_msgTypes,
	}.Build()
	File_sanction_v1_query_proto = out.File
	file_sanction_v1_query_proto_goTypes = nil
	file_sanction_v1_query_proto_depIdxs = nil
}
