// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sanction/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName            = "/sanction.v1.Query/Params"
	Query_Agent_FullMethodName             = "/sanction.v1.Query/Agent"
	Query_Agents_FullMethodName            = "/sanction.v1.Query/Agents"
	Query_RiskReport_FullMethodName        = "/sanction.v1.Query/RiskReport"
	Query_RiskReportsByTx_FullMethodName   = "/sanction.v1.Query/RiskReportsByTx"
	Query_SanctionCase_FullMethodName      = "/sanction.v1.Query/SanctionCase"
	Query_SanctionCasesByTx_FullMethodName = "/sanction.v1.Query/SanctionCasesByTx"
	Query_SanctionVotes_FullMethodName     = "/sanction.v1.Query/SanctionVotes"
	Query_ActiveTxSanction_FullMethodName  = "/sanction.v1.Query/ActiveTxSanction"
	Query_FrozenAddress_FullMethodName     = "/sanction.v1.Query/FrozenAddress"
	Query_ExecutionRecord_FullMethodName   = "/sanction.v1.Query/ExecutionRecord"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	Agent(ctx context.Context, in *QueryAgentRequest, opts ...grpc.CallOption) (*QueryAgentResponse, error)
	Agents(ctx context.Context, in *QueryAgentsRequest, opts ...grpc.CallOption) (*QueryAgentsResponse, error)
	RiskReport(ctx context.Context, in *QueryRiskReportRequest, opts ...grpc.CallOption) (*QueryRiskReportResponse, error)
	RiskReportsByTx(ctx context.Context, in *QueryRiskReportsByTxRequest, opts ...grpc.CallOption) (*QueryRiskReportsByTxResponse, error)
	SanctionCase(ctx context.Context, in *QuerySanctionCaseRequest, opts ...grpc.CallOption) (*QuerySanctionCaseResponse, error)
	SanctionCasesByTx(ctx context.Context, in *QuerySanctionCasesByTxRequest, opts ...grpc.CallOption) (*QuerySanctionCasesByTxResponse, error)
	SanctionVotes(ctx context.Context, in *QuerySanctionVotesRequest, opts ...grpc.CallOption) (*QuerySanctionVotesResponse, error)
	ActiveTxSanction(ctx context.Context, in *QueryActiveTxSanctionRequest, opts ...grpc.CallOption) (*QueryActiveTxSanctionResponse, error)
	FrozenAddress(ctx context.Context, in *QueryFrozenAddressRequest, opts ...grpc.CallOption) (*QueryFrozenAddressResponse, error)
	ExecutionRecord(ctx context.Context, in *QueryExecutionRecordRequest, opts ...grpc.CallOption) (*QueryExecutionRecordResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Agent(ctx context.Context, in *QueryAgentRequest, opts ...grpc.CallOption) (*QueryAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAgentResponse)
	err := c.cc.Invoke(ctx, Query_Agent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Agents(ctx context.Context, in *QueryAgentsRequest, opts ...grpc.CallOption) (*QueryAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAgentsResponse)
	err := c.cc.Invoke(ctx, Query_Agents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RiskReport(ctx context.Context, in *QueryRiskReportRequest, opts ...grpc.CallOption) (*QueryRiskReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRiskReportResponse)
	err := c.cc.Invoke(ctx, Query_RiskReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RiskReportsByTx(ctx context.Context, in *QueryRiskReportsByTxRequest, opts ...grpc.CallOption) (*QueryRiskReportsByTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRiskReportsByTxResponse)
	err := c.cc.Invoke(ctx, Query_RiskReportsByTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SanctionCase(ctx context.Context, in *QuerySanctionCaseRequest, opts ...grpc.CallOption) (*QuerySanctionCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySanctionCaseResponse)
	err := c.cc.Invoke(ctx, Query_SanctionCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SanctionCasesByTx(ctx context.Context, in *QuerySanctionCasesByTxRequest, opts ...grpc.CallOption) (*QuerySanctionCasesByTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySanctionCasesByTxResponse)
	err := c.cc.Invoke(ctx, Query_SanctionCasesByTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SanctionVotes(ctx context.Context, in *QuerySanctionVotesRequest, opts ...grpc.CallOption) (*QuerySanctionVotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySanctionVotesResponse)
	err := c.cc.Invoke(ctx, Query_SanctionVotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActiveTxSanction(ctx context.Context, in *QueryActiveTxSanctionRequest, opts ...grpc.CallOption) (*QueryActiveTxSanctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryActiveTxSanctionResponse)
	err := c.cc.Invoke(ctx, Query_ActiveTxSanction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FrozenAddress(ctx context.Context, in *QueryFrozenAddressRequest, opts ...grpc.CallOption) (*QueryFrozenAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFrozenAddressResponse)
	err := c.cc.Invoke(ctx, Query_FrozenAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ExecutionRecord(ctx context.Context, in *QueryExecutionRecordRequest, opts ...grpc.CallOption) (*QueryExecutionRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryExecutionRecordResponse)
	err := c.cc.Invoke(ctx, Query_ExecutionRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations should embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	Agent(context.Context, *QueryAgentRequest) (*QueryAgentResponse, error)
	Agents(context.Context, *QueryAgentsRequest) (*QueryAgentsResponse, error)
	RiskReport(context.Context, *QueryRiskReportRequest) (*QueryRiskReportResponse, error)
	RiskReportsByTx(context.Context, *QueryRiskReportsByTxRequest) (*QueryRiskReportsByTxResponse, error)
	SanctionCase(context.Context, *QuerySanctionCaseRequest) (*QuerySanctionCaseResponse, error)
	SanctionCasesByTx(context.Context, *QuerySanctionCasesByTxRequest) (*QuerySanctionCasesByTxResponse, error)
	SanctionVotes(context.Context, *QuerySanctionVotesRequest) (*QuerySanctionVotesResponse, error)
	ActiveTxSanction(context.Context, *QueryActiveTxSanctionRequest) (*QueryActiveTxSanctionResponse, error)
	FrozenAddress(context.Context, *QueryFrozenAddressRequest) (*QueryFrozenAddressResponse, error)
	ExecutionRecord(context.Context, *QueryExecutionRecordRequest) (*QueryExecutionRecordResponse, error)
}

// UnimplementedQueryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Agent(context.Context, *QueryAgentRequest) (*QueryAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Agent not implemented")
}
func (UnimplementedQueryServer) Agents(context.Context, *QueryAgentsRequest) (*QueryAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Agents not implemented")
}
func (UnimplementedQueryServer) RiskReport(context.Context, *QueryRiskReportRequest) (*QueryRiskReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RiskReport not implemented")
}
func (UnimplementedQueryServer) RiskReportsByTx(context.Context, *QueryRiskReportsByTxRequest) (*QueryRiskReportsByTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RiskReportsByTx not implemented")
}
func (UnimplementedQueryServer) SanctionCase(context.Context, *QuerySanctionCaseRequest) (*QuerySanctionCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SanctionCase not implemented")
}
func (UnimplementedQueryServer) SanctionCasesByTx(context.Context, *QuerySanctionCasesByTxRequest) (*QuerySanctionCasesByTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SanctionCasesByTx not implemented")
}
func (UnimplementedQueryServer) SanctionVotes(context.Context, *QuerySanctionVotesRequest) (*QuerySanctionVotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SanctionVotes not implemented")
}
func (UnimplementedQueryServer) ActiveTxSanction(context.Context, *QueryActiveTxSanctionRequest) (*QueryActiveTxSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveTxSanction not implemented")
}
func (UnimplementedQueryServer) FrozenAddress(context.Context, *QueryFrozenAddressRequest) (*QueryFrozenAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FrozenAddress not implemented")
}
func (UnimplementedQueryServer) ExecutionRecord(context.Context, *QueryExecutionRecordRequest) (*QueryExecutionRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutionRecord not implemented")
}
func (UnimplementedQueryServer) testEmbeddedByValue() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Agent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Agent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Agent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Agent(ctx, req.(*QueryAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Agents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Agents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Agents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Agents(ctx, req.(*QueryAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RiskReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRiskReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RiskReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_RiskReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RiskReport(ctx, req.(*QueryRiskReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RiskReportsByTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRiskReportsByTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RiskReportsByTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_RiskReportsByTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RiskReportsByTx(ctx, req.(*QueryRiskReportsByTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SanctionCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySanctionCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SanctionCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SanctionCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SanctionCase(ctx, req.(*QuerySanctionCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SanctionCasesByTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySanctionCasesByTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SanctionCasesByTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SanctionCasesByTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SanctionCasesByTx(ctx, req.(*QuerySanctionCasesByTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SanctionVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySanctionVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SanctionVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SanctionVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SanctionVotes(ctx, req.(*QuerySanctionVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActiveTxSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActiveTxSanctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveTxSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ActiveTxSanction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveTxSanction(ctx, req.(*QueryActiveTxSanctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FrozenAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFrozenAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FrozenAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FrozenAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FrozenAddress(ctx, req.(*QueryFrozenAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ExecutionRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExecutionRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ExecutionRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ExecutionRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ExecutionRecord(ctx, req.(*QueryExecutionRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sanction.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Agent",
			Handler:    _Query_Agent_Handler,
		},
		{
			MethodName: "Agents",
			Handler:    _Query_Agents_Handler,
		},
		{
			MethodName: "RiskReport",
			Handler:    _Query_RiskReport_Handler,
		},
		{
			MethodName: "RiskReportsByTx",
			Handler:    _Query_RiskReportsByTx_Handler,
		},
		{
			MethodName: "SanctionCase",
			Handler:    _Query_SanctionCase_Handler,
		},
		{
			MethodName: "SanctionCasesByTx",
			Handler:    _Query_SanctionCasesByTx_Handler,
		},
		{
			MethodName: "SanctionVotes",
			Handler:    _Query_SanctionVotes_Handler,
		},
		{
			MethodName: "ActiveTxSanction",
			Handler:    _Query_ActiveTxSanction_Handler,
		},
		{
			MethodName: "FrozenAddress",
			Handler:    _Query_FrozenAddress_Handler,
		},
		{
			MethodName: "ExecutionRecord",
			Handler:    _Query_ExecutionRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sanction/v1/query.proto",
}
