// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sanction/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgRegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Agent         *AgentInfo             `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterAgent) Reset() {
	*x = MsgRegisterAgent{}
	mi := &file_sanction_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterAgent) ProtoMessage() {}

func (x *MsgRegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterAgent.ProtoReflect.Descriptor instead.
func (*MsgRegisterAgent) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgRegisterAgent) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRegisterAgent) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type MsgRegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterAgentResponse) Reset() {
	*x = MsgRegisterAgentResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterAgentResponse) ProtoMessage() {}

func (x *MsgRegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{1}
}

type MsgSubmitRiskReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submitter     string                 `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Report        *RiskReport            `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitRiskReport) Reset() {
	*x = MsgSubmitRiskReport{}
	mi := &file_sanction_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitRiskReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitRiskReport) ProtoMessage() {}

func (x *MsgSubmitRiskReport) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitRiskReport.ProtoReflect.Descriptor instead.
func (*MsgSubmitRiskReport) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgSubmitRiskReport) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *MsgSubmitRiskReport) GetReport() *RiskReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type MsgSubmitRiskReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitRiskReportResponse) Reset() {
	*x = MsgSubmitRiskReportResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitRiskReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitRiskReportResponse) ProtoMessage() {}

func (x *MsgSubmitRiskReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitRiskReportResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitRiskReportResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgSubmitRiskReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type MsgOpenSanctionCase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Submitter       string                 `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	CaseId          string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TxHash          []byte                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress   string                 `protobuf:"bytes,4,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetType      SanctionTargetType     `protobuf:"varint,5,opt,name=target_type,json=targetType,proto3,enum=sanction.v1.SanctionTargetType" json:"target_type,omitempty"`
	RequestedAction SanctionAction         `protobuf:"varint,6,opt,name=requested_action,json=requestedAction,proto3,enum=sanction.v1.SanctionAction" json:"requested_action,omitempty"`
	ReportIds       []string               `protobuf:"bytes,7,rep,name=report_ids,json=reportIds,proto3" json:"report_ids,omitempty"`
	PolicyVersion   string                 `protobuf:"bytes,8,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgOpenSanctionCase) Reset() {
	*x = MsgOpenSanctionCase{}
	mi := &file_sanction_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgOpenSanctionCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgOpenSanctionCase) ProtoMessage() {}

func (x *MsgOpenSanctionCase) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgOpenSanctionCase.ProtoReflect.Descriptor instead.
func (*MsgOpenSanctionCase) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgOpenSanctionCase) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *MsgOpenSanctionCase) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *MsgOpenSanctionCase) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *MsgOpenSanctionCase) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *MsgOpenSanctionCase) GetTargetType() SanctionTargetType {
	if x != nil {
		return x.TargetType
	}
	return SanctionTargetType_SANCTION_TARGET_TYPE_UNSPECIFIED
}

func (x *MsgOpenSanctionCase) GetRequestedAction() SanctionAction {
	if x != nil {
		return x.RequestedAction
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (x *MsgOpenSanctionCase) GetReportIds() []string {
	if x != nil {
		return x.ReportIds
	}
	return nil
}

func (x *MsgOpenSanctionCase) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type MsgOpenSanctionCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgOpenSanctionCaseResponse) Reset() {
	*x = MsgOpenSanctionCaseResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgOpenSanctionCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgOpenSanctionCaseResponse) ProtoMessage() {}

func (x *MsgOpenSanctionCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgOpenSanctionCaseResponse.ProtoReflect.Descriptor instead.
func (*MsgOpenSanctionCaseResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgOpenSanctionCaseResponse) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type MsgSubmitSanctionVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submitter     string                 `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Vote          *SanctionVote          `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitSanctionVote) Reset() {
	*x = MsgSubmitSanctionVote{}
	mi := &file_sanction_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitSanctionVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitSanctionVote) ProtoMessage() {}

func (x *MsgSubmitSanctionVote) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitSanctionVote.ProtoReflect.Descriptor instead.
func (*MsgSubmitSanctionVote) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgSubmitSanctionVote) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *MsgSubmitSanctionVote) GetVote() *SanctionVote {
	if x != nil {
		return x.Vote
	}
	return nil
}

type MsgSubmitSanctionVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Rejected      bool                   `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitSanctionVoteResponse) Reset() {
	*x = MsgSubmitSanctionVoteResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitSanctionVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitSanctionVoteResponse) ProtoMessage() {}

func (x *MsgSubmitSanctionVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitSanctionVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitSanctionVoteResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgSubmitSanctionVoteResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *MsgSubmitSanctionVoteResponse) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

type MsgExecuteSanction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      string                 `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	CaseId        string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	ResultMessage string                 `protobuf:"bytes,3,opt,name=result_message,json=resultMessage,proto3" json:"result_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgExecuteSanction) Reset() {
	*x = MsgExecuteSanction{}
	mi := &file_sanction_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgExecuteSanction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgExecuteSanction) ProtoMessage() {}

func (x *MsgExecuteSanction) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgExecuteSanction.ProtoReflect.Descriptor instead.
func (*MsgExecuteSanction) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgExecuteSanction) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *MsgExecuteSanction) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *MsgExecuteSanction) GetResultMessage() string {
	if x != nil {
		return x.ResultMessage
	}
	return ""
}

type MsgExecuteSanctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExecutionRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgExecuteSanctionResponse) Reset() {
	*x = MsgExecuteSanctionResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgExecuteSanctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgExecuteSanctionResponse) ProtoMessage() {}

func (x *MsgExecuteSanctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgExecuteSanctionResponse.ProtoReflect.Descriptor instead.
func (*MsgExecuteSanctionResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MsgExecuteSanctionResponse) GetRecord() *ExecutionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type MsgRevokeSanction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	CaseId        string                 `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevokeSanction) Reset() {
	*x = MsgRevokeSanction{}
	mi := &file_sanction_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevokeSanction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevokeSanction) ProtoMessage() {}

func (x *MsgRevokeSanction) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevokeSanction.ProtoReflect.Descriptor instead.
func (*MsgRevokeSanction) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgRevokeSanction) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgRevokeSanction) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *MsgRevokeSanction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MsgRevokeSanctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevokeSanctionResponse) Reset() {
	*x = MsgRevokeSanctionResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevokeSanctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevokeSanctionResponse) ProtoMessage() {}

func (x *MsgRevokeSanctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevokeSanctionResponse.ProtoReflect.Descriptor instead.
func (*MsgRevokeSanctionResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{11}
}

type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_sanction_v1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{12}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_sanction_v1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_sanction_v1_tx_proto_rawDescGZIP(), []int{13}
}

var File_sanction_v1_tx_proto protoreflect.FileDescriptor

const file_sanction_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x14sanction/v1/tx.proto\x12\vsanction.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19sanction/v1/genesis.proto\x1a\x17sanction/v1/types.proto\"n\n" +
	"\x10MsgRegisterAgent\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12,\n" +
	"\x05agent\x18\x02 \x01(\v2\x16.sanction.v1.AgentInfoR\x05agent:\x0e\x82\xe7\xb0*\tauthority\"\x1a\n" +
	"\x18MsgRegisterAgentResponse\"t\n" +
	"\x13MsgSubmitRiskReport\x12\x1c\n" +
	"\tsubmitter\x18\x01 \x01(\tR\tsubmitter\x12/\n" +
	"\x06report\x18\x02 \x01(\v2\x17.sanction.v1.RiskReportR\x06report:\x0e\x82\xe7\xb0*\tsubmitter\":\n" +
	"\x1bMsgSubmitRiskReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"\xec\x02\n" +
	"\x13MsgOpenSanctionCase\x12\x1c\n" +
	"\tsubmitter\x18\x01 \x01(\tR\tsubmitter\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\fR\x06txHash\x12%\n" +
	"\x0etarget_address\x18\x04 \x01(\tR\rtargetAddress\x12@\n" +
	"\vtarget_type\x18\x05 \x01(\x0e2\x1f.sanction.v1.SanctionTargetTypeR\n" +
	"targetType\x12F\n" +
	"\x10requested_action\x18\x06 \x01(\x0e2\x1b.sanction.v1.SanctionActionR\x0frequestedAction\x12\x1d\n" +
	"\n" +
	"report_ids\x18\a \x03(\tR\treportIds\x12%\n" +
	"\x0epolicy_version\x18\b \x01(\tR\rpolicyVersion:\x0e\x82\xe7\xb0*\tsubmitter\"6\n" +
	"\x1bMsgOpenSanctionCaseResponse\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"t\n" +
	"\x15MsgSubmitSanctionVote\x12\x1c\n" +
	"\tsubmitter\x18\x01 \x01(\tR\tsubmitter\x12-\n" +
	"\x04vote\x18\x02 \x01(\v2\x19.sanction.v1.SanctionVoteR\x04vote:\x0e\x82\xe7\xb0*\tsubmitter\"W\n" +
	"\x1dMsgSubmitSanctionVoteResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\bR\brejected\"\x7f\n" +
	"\x12MsgExecuteSanction\x12\x1a\n" +
	"\bexecutor\x18\x01 \x01(\tR\bexecutor\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12%\n" +
	"\x0eresult_message\x18\x03 \x01(\tR\rresultMessage:\r\x82\xe7\xb0*\bexecutor\"R\n" +
	"\x1aMsgExecuteSanctionResponse\x124\n" +
	"\x06record\x18\x01 \x01(\v2\x1c.sanction.v1.ExecutionRecordR\x06record\"r\n" +
	"\x11MsgRevokeSanction\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason:\x0e\x82\xe7\xb0*\tauthority\"\x1b\n" +
	"\x19MsgRevokeSanctionResponse\"l\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12+\n" +
	"\x06params\x18\x02 \x01(\v2\x13.sanction.v1.ParamsR\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\x94\x05\n" +
	"\x03Msg\x12U\n" +
	"\rRegisterAgent\x12\x1d.sanction.v1.MsgRegisterAgent\x1a%.sanction.v1.MsgRegisterAgentResponse\x12^\n" +
	"\x10SubmitRiskReport\x12 .sanction.v1.MsgSubmitRiskReport\x1a(.sanction.v1.MsgSubmitRiskReportResponse\x12^\n" +
	"\x10OpenSanctionCase\x12 .sanction.v1.MsgOpenSanctionCase\x1a(.sanction.v1.MsgOpenSanctionCaseResponse\x12d\n" +
	"\x12SubmitSanctionVote\x12\".sanction.v1.MsgSubmitSanctionVote\x1a*.sanction.v1.MsgSubmitSanctionVoteResponse\x12[\n" +
	"\x0fExecuteSanction\x12\x1f.sanction.v1.MsgExecuteSanction\x1a'.sanction.v1.MsgExecuteSanctionResponse\x12X\n" +
	"\x0eRevokeSanction\x12\x1e.sanction.v1.MsgRevokeSanction\x1a&.sanction.v1.MsgRevokeSanctionResponse\x12R\n" +
	"\fUpdateParams\x12\x1c.sanction.v1.MsgUpdateParams\x1a$.sanction.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B5Z3github.com/crossref/crossref-chain/x/sanction/typesb\x06proto3"

var (
	file_sanction_v1_tx_proto_rawDescOnce sync.Once
	file_sanction_v1_tx_proto_rawDescData []byte
)

func file_sanction_v1_tx_proto_rawDescGZIP() []byte {
	file_sanction_v1_tx_proto_rawDescOnce.Do(func() {
		file_sanction_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sanction_v1_tx_proto_rawDesc), len(file_sanction_v1_tx_proto_rawDesc)))
	})
	return file_sanction_v1_tx_proto_rawDescData
}

var file_sanction_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sanction_v1_tx_proto_goTypes = []any{
	(*MsgRegisterAgent)(nil),              // 0: sanction.v1.MsgRegisterAgent
	(*MsgRegisterAgentResponse)(nil),      // 1: sanction.v1.MsgRegisterAgentResponse
	(*MsgSubmitRiskReport)(nil),           // 2: sanction.v1.MsgSubmitRiskReport
	(*MsgSubmitRiskReportResponse)(nil),   // 3: sanction.v1.MsgSubmitRiskReportResponse
	(*MsgOpenSanctionCase)(nil),           // 4: sanction.v1.MsgOpenSanctionCase
	(*MsgOpenSanctionCaseResponse)(nil),   // 5: sanction.v1.MsgOpenSanctionCaseResponse
	(*MsgSubmitSanctionVote)(nil),         // 6: sanction.v1.MsgSubmitSanctionVote
	(*MsgSubmitSanctionVoteResponse)(nil), // 7: sanction.v1.MsgSubmitSanctionVoteResponse
	(*MsgExecuteSanction)(nil),            // 8: sanction.v1.MsgExecuteSanction
	(*MsgExecuteSanctionResponse)(nil),    // 9: sanction.v1.MsgExecuteSanctionResponse
	(*MsgRevokeSanction)(nil),             // 10: sanction.v1.MsgRevokeSanction
	(*MsgRevokeSanctionResponse)(nil),     // 11: sanction.v1.MsgRevokeSanctionResponse
	(*MsgUpdateParams)(nil),               // 12: sanction.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),       // 13: sanction.v1.MsgUpdateParamsResponse
	(*AgentInfo)(nil),                     // 14: sanction.v1.AgentInfo
	(*RiskReport)(nil),                    // 15: sanction.v1.RiskReport
	(SanctionTargetType)(0),               // 16: sanction.v1.SanctionTargetType
	(SanctionAction)(0),                   // 17: sanction.v1.SanctionAction
	(*SanctionVote)(nil),                  // 18: sanction.v1.SanctionVote
	(*ExecutionRecord)(nil),               // 19: sanction.v1.ExecutionRecord
	(*Params)(nil),                        // 20: sanction.v1.Params
}
var file_sanction_v1_tx_proto_depIdxs = []int32{
	14, // 0: sanction.v1.MsgRegisterAgent.agent:type_name -> sanction.v1.AgentInfo
	15, // 1: sanction.v1.MsgSubmitRiskReport.report:type_name -> sanction.v1.RiskReport
	16, // 2: sanction.v1.MsgOpenSanctionCase.target_type:type_name -> sanction.v1.SanctionTargetType
	17, // 3: sanction.v1.MsgOpenSanctionCase.requested_action:type_name -> sanction.v1.SanctionAction
	18, // 4: sanction.v1.MsgSubmitSanctionVote.vote:type_name -> sanction.v1.SanctionVote
	19, // 5: sanction.v1.MsgExecuteSanctionResponse.record:type_name -> sanction.v1.ExecutionRecord
	20, // 6: sanction.v1.MsgUpdateParams.params:type_name -> sanction.v1.Params
	0,  // 7: sanction.v1.Msg.RegisterAgent:input_type -> sanction.v1.MsgRegisterAgent
	2,  // 8: sanction.v1.Msg.SubmitRiskReport:input_type -> sanction.v1.MsgSubmitRiskReport
	4,  // 9: sanction.v1.Msg.OpenSanctionCase:input_type -> sanction.v1.MsgOpenSanctionCase
	6,  // 10: sanction.v1.Msg.SubmitSanctionVote:input_type -> sanction.v1.MsgSubmitSanctionVote
	8,  // 11: sanction.v1.Msg.ExecuteSanction:input_type -> sanction.v1.MsgExecuteSanction
	10, // 12: sanction.v1.Msg.RevokeSanction:input_type -> sanction.v1.MsgRevokeSanction
	12, // 13: sanction.v1.Msg.UpdateParams:input_type -> sanction.v1.MsgUpdateParams
	1,  // 14: sanction.v1.Msg.RegisterAgent:output_type -> sanction.v1.MsgRegisterAgentResponse
	3,  // 15: sanction.v1.Msg.SubmitRiskReport:output_type -> sanction.v1.MsgSubmitRiskReportResponse
	5,  // 16: sanction.v1.Msg.OpenSanctionCase:output_type -> sanction.v1.MsgOpenSanctionCaseResponse
	7,  // 17: sanction.v1.Msg.SubmitSanctionVote:output_type -> sanction.v1.MsgSubmitSanctionVoteResponse
	9,  // 18: sanction.v1.Msg.ExecuteSanction:output_type -> sanction.v1.MsgExecuteSanctionResponse
	11, // 19: sanction.v1.Msg.RevokeSanction:output_type -> sanction.v1.MsgRevokeSanctionResponse
	13, // 20: sanction.v1.Msg.UpdateParams:output_type -> sanction.v1.MsgUpdateParamsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sanction_v1_tx_proto_init() }
func file_sanction_v1_tx_proto_init() {
	if File_sanction_v1_tx_proto != nil {
		return
	}
	file_sanction_v1_genesis_proto_init()
	file_sanction_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sanction_v1_tx_proto_rawDesc), len(file_sanction_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sanction_v1_tx_proto_goTypes,
		DependencyIndexes: file_sanction_v1_tx_proto_depIdxs,
		MessageInfos:      file_sanction_v1_tx_proto_msgTypes,
	}.Build()
	File_sanction_v1_tx_proto = out.File
	file_sanction_v1_tx_proto_goTypes = nil
	file_sanction_v1_tx_proto_depIdxs = nil
}
