// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sanction/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_RegisterAgent_FullMethodName      = "/sanction.v1.Msg/RegisterAgent"
	Msg_SubmitRiskReport_FullMethodName   = "/sanction.v1.Msg/SubmitRiskReport"
	Msg_OpenSanctionCase_FullMethodName   = "/sanction.v1.Msg/OpenSanctionCase"
	Msg_SubmitSanctionVote_FullMethodName = "/sanction.v1.Msg/SubmitSanctionVote"
	Msg_ExecuteSanction_FullMethodName    = "/sanction.v1.Msg/ExecuteSanction"
	Msg_RevokeSanction_FullMethodName     = "/sanction.v1.Msg/RevokeSanction"
	Msg_UpdateParams_FullMethodName       = "/sanction.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	RegisterAgent(ctx context.Context, in *MsgRegisterAgent, opts ...grpc.CallOption) (*MsgRegisterAgentResponse, error)
	SubmitRiskReport(ctx context.Context, in *MsgSubmitRiskReport, opts ...grpc.CallOption) (*MsgSubmitRiskReportResponse, error)
	OpenSanctionCase(ctx context.Context, in *MsgOpenSanctionCase, opts ...grpc.CallOption) (*MsgOpenSanctionCaseResponse, error)
	SubmitSanctionVote(ctx context.Context, in *MsgSubmitSanctionVote, opts ...grpc.CallOption) (*MsgSubmitSanctionVoteResponse, error)
	ExecuteSanction(ctx context.Context, in *MsgExecuteSanction, opts ...grpc.CallOption) (*MsgExecuteSanctionResponse, error)
	RevokeSanction(ctx context.Context, in *MsgRevokeSanction, opts ...grpc.CallOption) (*MsgRevokeSanctionResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterAgent(ctx context.Context, in *MsgRegisterAgent, opts ...grpc.CallOption) (*MsgRegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterAgentResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitRiskReport(ctx context.Context, in *MsgSubmitRiskReport, opts ...grpc.CallOption) (*MsgSubmitRiskReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitRiskReportResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitRiskReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) OpenSanctionCase(ctx context.Context, in *MsgOpenSanctionCase, opts ...grpc.CallOption) (*MsgOpenSanctionCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgOpenSanctionCaseResponse)
	err := c.cc.Invoke(ctx, Msg_OpenSanctionCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitSanctionVote(ctx context.Context, in *MsgSubmitSanctionVote, opts ...grpc.CallOption) (*MsgSubmitSanctionVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitSanctionVoteResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitSanctionVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteSanction(ctx context.Context, in *MsgExecuteSanction, opts ...grpc.CallOption) (*MsgExecuteSanctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgExecuteSanctionResponse)
	err := c.cc.Invoke(ctx, Msg_ExecuteSanction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeSanction(ctx context.Context, in *MsgRevokeSanction, opts ...grpc.CallOption) (*MsgRevokeSanctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevokeSanctionResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeSanction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations should embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	RegisterAgent(context.Context, *MsgRegisterAgent) (*MsgRegisterAgentResponse, error)
	SubmitRiskReport(context.Context, *MsgSubmitRiskReport) (*MsgSubmitRiskReportResponse, error)
	OpenSanctionCase(context.Context, *MsgOpenSanctionCase) (*MsgOpenSanctionCaseResponse, error)
	SubmitSanctionVote(context.Context, *MsgSubmitSanctionVote) (*MsgSubmitSanctionVoteResponse, error)
	ExecuteSanction(context.Context, *MsgExecuteSanction) (*MsgExecuteSanctionResponse, error)
	RevokeSanction(context.Context, *MsgRevokeSanction) (*MsgRevokeSanctionResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) RegisterAgent(context.Context, *MsgRegisterAgent) (*MsgRegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedMsgServer) SubmitRiskReport(context.Context, *MsgSubmitRiskReport) (*MsgSubmitRiskReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRiskReport not implemented")
}
func (UnimplementedMsgServer) OpenSanctionCase(context.Context, *MsgOpenSanctionCase) (*MsgOpenSanctionCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSanctionCase not implemented")
}
func (UnimplementedMsgServer) SubmitSanctionVote(context.Context, *MsgSubmitSanctionVote) (*MsgSubmitSanctionVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSanctionVote not implemented")
}
func (UnimplementedMsgServer) ExecuteSanction(context.Context, *MsgExecuteSanction) (*MsgExecuteSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSanction not implemented")
}
func (UnimplementedMsgServer) RevokeSanction(context.Context, *MsgRevokeSanction) (*MsgRevokeSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSanction not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) testEmbeddedByValue() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterAgent(ctx, req.(*MsgRegisterAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitRiskReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitRiskReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitRiskReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitRiskReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitRiskReport(ctx, req.(*MsgSubmitRiskReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_OpenSanctionCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenSanctionCase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenSanctionCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_OpenSanctionCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenSanctionCase(ctx, req.(*MsgOpenSanctionCase))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitSanctionVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitSanctionVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitSanctionVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitSanctionVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitSanctionVote(ctx, req.(*MsgSubmitSanctionVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteSanction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ExecuteSanction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteSanction(ctx, req.(*MsgExecuteSanction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeSanction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeSanction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeSanction(ctx, req.(*MsgRevokeSanction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sanction.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _Msg_RegisterAgent_Handler,
		},
		{
			MethodName: "SubmitRiskReport",
			Handler:    _Msg_SubmitRiskReport_Handler,
		},
		{
			MethodName: "OpenSanctionCase",
			Handler:    _Msg_OpenSanctionCase_Handler,
		},
		{
			MethodName: "SubmitSanctionVote",
			Handler:    _Msg_SubmitSanctionVote_Handler,
		},
		{
			MethodName: "ExecuteSanction",
			Handler:    _Msg_ExecuteSanction_Handler,
		},
		{
			MethodName: "RevokeSanction",
			Handler:    _Msg_RevokeSanction_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sanction/v1/tx.proto",
}
