// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sanction/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SanctionTargetType int32

const (
	SanctionTargetType_SANCTION_TARGET_TYPE_UNSPECIFIED SanctionTargetType = 0
	SanctionTargetType_SANCTION_TARGET_TYPE_TX          SanctionTargetType = 1
	SanctionTargetType_SANCTION_TARGET_TYPE_ADDRESS     SanctionTargetType = 2
)

// Enum value maps for SanctionTargetType.
var (
	SanctionTargetType_name = map[int32]string{
		0: "SANCTION_TARGET_TYPE_UNSPECIFIED",
		1: "SANCTION_TARGET_TYPE_TX",
		2: "SANCTION_TARGET_TYPE_ADDRESS",
	}
	SanctionTargetType_value = map[string]int32{
		"SANCTION_TARGET_TYPE_UNSPECIFIED": 0,
		"SANCTION_TARGET_TYPE_TX":          1,
		"SANCTION_TARGET_TYPE_ADDRESS":     2,
	}
)

func (x SanctionTargetType) Enum() *SanctionTargetType {
	p := new(SanctionTargetType)
	*p = x
	return p
}

func (x SanctionTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SanctionTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_sanction_v1_types_proto_enumTypes[0].Descriptor()
}

func (SanctionTargetType) Type() protoreflect.EnumType {
	return &file_sanction_v1_types_proto_enumTypes[0]
}

func (x SanctionTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SanctionTargetType.Descriptor instead.
func (SanctionTargetType) EnumDescriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{0}
}

type SanctionAction int32

const (
	SanctionAction_SANCTION_ACTION_UNSPECIFIED     SanctionAction = 0
	SanctionAction_SANCTION_ACTION_WATCH           SanctionAction = 1
	SanctionAction_SANCTION_ACTION_BLOCK_TX        SanctionAction = 2
	SanctionAction_SANCTION_ACTION_FREEZE_ADDRESS  SanctionAction = 3
	SanctionAction_SANCTION_ACTION_ESCROW_FUNDS    SanctionAction = 4
	SanctionAction_SANCTION_ACTION_REVERT_TRANSFER SanctionAction = 5
)

// Enum value maps for SanctionAction.
var (
	SanctionAction_name = map[int32]string{
		0: "SANCTION_ACTION_UNSPECIFIED",
		1: "SANCTION_ACTION_WATCH",
		2: "SANCTION_ACTION_BLOCK_TX",
		3: "SANCTION_ACTION_FREEZE_ADDRESS",
		4: "SANCTION_ACTION_ESCROW_FUNDS",
		5: "SANCTION_ACTION_REVERT_TRANSFER",
	}
	SanctionAction_value = map[string]int32{
		"SANCTION_ACTION_UNSPECIFIED":     0,
		"SANCTION_ACTION_WATCH":           1,
		"SANCTION_ACTION_BLOCK_TX":        2,
		"SANCTION_ACTION_FREEZE_ADDRESS":  3,
		"SANCTION_ACTION_ESCROW_FUNDS":    4,
		"SANCTION_ACTION_REVERT_TRANSFER": 5,
	}
)

func (x SanctionAction) Enum() *SanctionAction {
	p := new(SanctionAction)
	*p = x
	return p
}

func (x SanctionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SanctionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_sanction_v1_types_proto_enumTypes[1].Descriptor()
}

func (SanctionAction) Type() protoreflect.EnumType {
	return &file_sanction_v1_types_proto_enumTypes[1]
}

func (x SanctionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SanctionAction.Descriptor instead.
func (SanctionAction) EnumDescriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{1}
}

type CaseStatus int32

const (
	CaseStatus_CASE_STATUS_UNSPECIFIED CaseStatus = 0
	CaseStatus_CASE_STATUS_PENDING     CaseStatus = 1
	CaseStatus_CASE_STATUS_APPROVED    CaseStatus = 2
	CaseStatus_CASE_STATUS_REJECTED    CaseStatus = 3
	CaseStatus_CASE_STATUS_EXECUTED    CaseStatus = 4
	CaseStatus_CASE_STATUS_EXPIRED     CaseStatus = 5
	CaseStatus_CASE_STATUS_REVOKED     CaseStatus = 6
)

// Enum value maps for CaseStatus.
var (
	CaseStatus_name = map[int32]string{
		0: "CASE_STATUS_UNSPECIFIED",
		1: "CASE_STATUS_PENDING",
		2: "CASE_STATUS_APPROVED",
		3: "CASE_STATUS_REJECTED",
		4: "CASE_STATUS_EXECUTED",
		5: "CASE_STATUS_EXPIRED",
		6: "CASE_STATUS_REVOKED",
	}
	CaseStatus_value = map[string]int32{
		"CASE_STATUS_UNSPECIFIED": 0,
		"CASE_STATUS_PENDING":     1,
		"CASE_STATUS_APPROVED":    2,
		"CASE_STATUS_REJECTED":    3,
		"CASE_STATUS_EXECUTED":    4,
		"CASE_STATUS_EXPIRED":     5,
		"CASE_STATUS_REVOKED":     6,
	}
)

func (x CaseStatus) Enum() *CaseStatus {
	p := new(CaseStatus)
	*p = x
	return p
}

func (x CaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sanction_v1_types_proto_enumTypes[2].Descriptor()
}

func (CaseStatus) Type() protoreflect.EnumType {
	return &file_sanction_v1_types_proto_enumTypes[2]
}

func (x CaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseStatus.Descriptor instead.
func (CaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{2}
}

type VoteOption int32

const (
	VoteOption_VOTE_OPTION_UNSPECIFIED VoteOption = 0
	VoteOption_VOTE_OPTION_APPROVE     VoteOption = 1
	VoteOption_VOTE_OPTION_REJECT      VoteOption = 2
	VoteOption_VOTE_OPTION_ABSTAIN     VoteOption = 3
)

// Enum value maps for VoteOption.
var (
	VoteOption_name = map[int32]string{
		0: "VOTE_OPTION_UNSPECIFIED",
		1: "VOTE_OPTION_APPROVE",
		2: "VOTE_OPTION_REJECT",
		3: "VOTE_OPTION_ABSTAIN",
	}
	VoteOption_value = map[string]int32{
		"VOTE_OPTION_UNSPECIFIED": 0,
		"VOTE_OPTION_APPROVE":     1,
		"VOTE_OPTION_REJECT":      2,
		"VOTE_OPTION_ABSTAIN":     3,
	}
)

func (x VoteOption) Enum() *VoteOption {
	p := new(VoteOption)
	*p = x
	return p
}

func (x VoteOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteOption) Descriptor() protoreflect.EnumDescriptor {
	return file_sanction_v1_types_proto_enumTypes[3].Descriptor()
}

func (VoteOption) Type() protoreflect.EnumType {
	return &file_sanction_v1_types_proto_enumTypes[3]
}

func (x VoteOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteOption.Descriptor instead.
func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{3}
}

type AgentInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AgentId                  string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ValidatorOperatorAddress string                 `protobuf:"bytes,2,opt,name=validator_operator_address,json=validatorOperatorAddress,proto3" json:"validator_operator_address,omitempty"`
	SignerAddress            string                 `protobuf:"bytes,3,opt,name=signer_address,json=signerAddress,proto3" json:"signer_address,omitempty"`
	PublicKey                []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	VotingPower              uint64                 `protobuf:"varint,5,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	Active                   bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	MetadataUri              string                 `protobuf:"bytes,7,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_sanction_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetValidatorOperatorAddress() string {
	if x != nil {
		return x.ValidatorOperatorAddress
	}
	return ""
}

func (x *AgentInfo) GetSignerAddress() string {
	if x != nil {
		return x.SignerAddress
	}
	return ""
}

func (x *AgentInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AgentInfo) GetVotingPower() uint64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *AgentInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AgentInfo) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

type RiskReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReportId           string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	TxHash             []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Sender             string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient          string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Denom              string                 `protobuf:"bytes,5,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount             string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Source             string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	SourceResponseId   string                 `protobuf:"bytes,8,opt,name=source_response_id,json=sourceResponseId,proto3" json:"source_response_id,omitempty"`
	RiskScore          uint32                 `protobuf:"varint,9,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RiskCategories     []string               `protobuf:"bytes,10,rep,name=risk_categories,json=riskCategories,proto3" json:"risk_categories,omitempty"`
	ExposureType       string                 `protobuf:"bytes,11,opt,name=exposure_type,json=exposureType,proto3" json:"exposure_type,omitempty"`
	ObservedHeight     uint64                 `protobuf:"varint,12,opt,name=observed_height,json=observedHeight,proto3" json:"observed_height,omitempty"`
	ExpiryHeight       uint64                 `protobuf:"varint,13,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	PolicyVersion      string                 `protobuf:"bytes,14,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	EvidenceHash       []byte                 `protobuf:"bytes,15,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	LlmRationaleHash   []byte                 `protobuf:"bytes,16,opt,name=llm_rationale_hash,json=llmRationaleHash,proto3" json:"llm_rationale_hash,omitempty"`
	Submitter          string                 `protobuf:"bytes,17,opt,name=submitter,proto3" json:"submitter,omitempty"`
	SubmitterSignature []byte                 `protobuf:"bytes,18,opt,name=submitter_signature,json=submitterSignature,proto3" json:"submitter_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RiskReport) Reset() {
	*x = RiskReport{}
	mi := &file_sanction_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskReport) ProtoMessage() {}

func (x *RiskReport) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskReport.ProtoReflect.Descriptor instead.
func (*RiskReport) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *RiskReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RiskReport) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *RiskReport) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *RiskReport) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *RiskReport) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *RiskReport) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RiskReport) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RiskReport) GetSourceResponseId() string {
	if x != nil {
		return x.SourceResponseId
	}
	return ""
}

func (x *RiskReport) GetRiskScore() uint32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskReport) GetRiskCategories() []string {
	if x != nil {
		return x.RiskCategories
	}
	return nil
}

func (x *RiskReport) GetExposureType() string {
	if x != nil {
		return x.ExposureType
	}
	return ""
}

func (x *RiskReport) GetObservedHeight() uint64 {
	if x != nil {
		return x.ObservedHeight
	}
	return 0
}

func (x *RiskReport) GetExpiryHeight() uint64 {
	if x != nil {
		return x.ExpiryHeight
	}
	return 0
}

func (x *RiskReport) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *RiskReport) GetEvidenceHash() []byte {
	if x != nil {
		return x.EvidenceHash
	}
	return nil
}

func (x *RiskReport) GetLlmRationaleHash() []byte {
	if x != nil {
		return x.LlmRationaleHash
	}
	return nil
}

func (x *RiskReport) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *RiskReport) GetSubmitterSignature() []byte {
	if x != nil {
		return x.SubmitterSignature
	}
	return nil
}

type SanctionCase struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CaseId               string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TxHash               []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress        string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetType           SanctionTargetType     `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3,enum=sanction.v1.SanctionTargetType" json:"target_type,omitempty"`
	RequestedAction      SanctionAction         `protobuf:"varint,5,opt,name=requested_action,json=requestedAction,proto3,enum=sanction.v1.SanctionAction" json:"requested_action,omitempty"`
	Status               CaseStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=sanction.v1.CaseStatus" json:"status,omitempty"`
	ReportIds            []string               `protobuf:"bytes,7,rep,name=report_ids,json=reportIds,proto3" json:"report_ids,omitempty"`
	OpenedHeight         uint64                 `protobuf:"varint,8,opt,name=opened_height,json=openedHeight,proto3" json:"opened_height,omitempty"`
	VotingDeadlineHeight uint64                 `protobuf:"varint,9,opt,name=voting_deadline_height,json=votingDeadlineHeight,proto3" json:"voting_deadline_height,omitempty"`
	ExecutedHeight       uint64                 `protobuf:"varint,10,opt,name=executed_height,json=executedHeight,proto3" json:"executed_height,omitempty"`
	PolicyVersion        string                 `protobuf:"bytes,11,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	DecisionHash         []byte                 `protobuf:"bytes,12,opt,name=decision_hash,json=decisionHash,proto3" json:"decision_hash,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SanctionCase) Reset() {
	*x = SanctionCase{}
	mi := &file_sanction_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanctionCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanctionCase) ProtoMessage() {}

func (x *SanctionCase) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanctionCase.ProtoReflect.Descriptor instead.
func (*SanctionCase) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *SanctionCase) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *SanctionCase) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *SanctionCase) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *SanctionCase) GetTargetType() SanctionTargetType {
	if x != nil {
		return x.TargetType
	}
	return SanctionTargetType_SANCTION_TARGET_TYPE_UNSPECIFIED
}

func (x *SanctionCase) GetRequestedAction() SanctionAction {
	if x != nil {
		return x.RequestedAction
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (x *SanctionCase) GetStatus() CaseStatus {
	if x != nil {
		return x.Status
	}
	return CaseStatus_CASE_STATUS_UNSPECIFIED
}

func (x *SanctionCase) GetReportIds() []string {
	if x != nil {
		return x.ReportIds
	}
	return nil
}

func (x *SanctionCase) GetOpenedHeight() uint64 {
	if x != nil {
		return x.OpenedHeight
	}
	return 0
}

func (x *SanctionCase) GetVotingDeadlineHeight() uint64 {
	if x != nil {
		return x.VotingDeadlineHeight
	}
	return 0
}

func (x *SanctionCase) GetExecutedHeight() uint64 {
	if x != nil {
		return x.ExecutedHeight
	}
	return 0
}

func (x *SanctionCase) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *SanctionCase) GetDecisionHash() []byte {
	if x != nil {
		return x.DecisionHash
	}
	return nil
}

type SanctionVote struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CaseId         string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Option         VoteOption             `protobuf:"varint,3,opt,name=option,proto3,enum=sanction.v1.VoteOption" json:"option,omitempty"`
	ApprovedAction SanctionAction         `protobuf:"varint,4,opt,name=approved_action,json=approvedAction,proto3,enum=sanction.v1.SanctionAction" json:"approved_action,omitempty"`
	ReasonCode     string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	RationaleHash  []byte                 `protobuf:"bytes,6,opt,name=rationale_hash,json=rationaleHash,proto3" json:"rationale_hash,omitempty"`
	SignedHeight   uint64                 `protobuf:"varint,7,opt,name=signed_height,json=signedHeight,proto3" json:"signed_height,omitempty"`
	Signature      []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SanctionVote) Reset() {
	*x = SanctionVote{}
	mi := &file_sanction_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanctionVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanctionVote) ProtoMessage() {}

func (x *SanctionVote) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanctionVote.ProtoReflect.Descriptor instead.
func (*SanctionVote) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *SanctionVote) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *SanctionVote) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SanctionVote) GetOption() VoteOption {
	if x != nil {
		return x.Option
	}
	return VoteOption_VOTE_OPTION_UNSPECIFIED
}

func (x *SanctionVote) GetApprovedAction() SanctionAction {
	if x != nil {
		return x.ApprovedAction
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (x *SanctionVote) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *SanctionVote) GetRationaleHash() []byte {
	if x != nil {
		return x.RationaleHash
	}
	return nil
}

func (x *SanctionVote) GetSignedHeight() uint64 {
	if x != nil {
		return x.SignedHeight
	}
	return 0
}

func (x *SanctionVote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ActiveSanction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CaseId          string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TxHash          []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress   string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	Action          SanctionAction         `protobuf:"varint,4,opt,name=action,proto3,enum=sanction.v1.SanctionAction" json:"action,omitempty"`
	ActivatedHeight uint64                 `protobuf:"varint,5,opt,name=activated_height,json=activatedHeight,proto3" json:"activated_height,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActiveSanction) Reset() {
	*x = ActiveSanction{}
	mi := &file_sanction_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSanction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSanction) ProtoMessage() {}

func (x *ActiveSanction) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSanction.ProtoReflect.Descriptor instead.
func (*ActiveSanction) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *ActiveSanction) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ActiveSanction) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ActiveSanction) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *ActiveSanction) GetAction() SanctionAction {
	if x != nil {
		return x.Action
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (x *ActiveSanction) GetActivatedHeight() uint64 {
	if x != nil {
		return x.ActivatedHeight
	}
	return 0
}

type FreezeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FrozenHeight  uint64                 `protobuf:"varint,3,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeRecord) Reset() {
	*x = FreezeRecord{}
	mi := &file_sanction_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeRecord) ProtoMessage() {}

func (x *FreezeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeRecord.ProtoReflect.Descriptor instead.
func (*FreezeRecord) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *FreezeRecord) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *FreezeRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FreezeRecord) GetFrozenHeight() uint64 {
	if x != nil {
		return x.FrozenHeight
	}
	return 0
}

type ExecutionRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CaseId          string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Action          SanctionAction         `protobuf:"varint,2,opt,name=action,proto3,enum=sanction.v1.SanctionAction" json:"action,omitempty"`
	TxHash          []byte                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress   string                 `protobuf:"bytes,4,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	Executor        string                 `protobuf:"bytes,5,opt,name=executor,proto3" json:"executor,omitempty"`
	ExecutedHeight  uint64                 `protobuf:"varint,6,opt,name=executed_height,json=executedHeight,proto3" json:"executed_height,omitempty"`
	ResultCode      string                 `protobuf:"bytes,7,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	ResultMessage   string                 `protobuf:"bytes,8,opt,name=result_message,json=resultMessage,proto3" json:"result_message,omitempty"`
	StateChangeHash []byte                 `protobuf:"bytes,9,opt,name=state_change_hash,json=stateChangeHash,proto3" json:"state_change_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_sanction_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sanction_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_sanction_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionRecord) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ExecutionRecord) GetAction() SanctionAction {
	if x != nil {
		return x.Action
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (x *ExecutionRecord) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ExecutionRecord) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *ExecutionRecord) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *ExecutionRecord) GetExecutedHeight() uint64 {
	if x != nil {
		return x.ExecutedHeight
	}
	return 0
}

func (x *ExecutionRecord) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *ExecutionRecord) GetResultMessage() string {
	if x != nil {
		return x.ResultMessage
	}
	return ""
}

func (x *ExecutionRecord) GetStateChangeHash() []byte {
	if x != nil {
		return x.StateChangeHash
	}
	return nil
}

var File_sanction_v1_types_proto protoreflect.FileDescriptor

const file_sanction_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x17sanction/v1/types.proto\x12\vsanction.v1\"\x88\x02\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12<\n" +
	"\x1avalidator_operator_address\x18\x02 \x01(\tR\x18validatorOperatorAddress\x12%\n" +
	"\x0esigner_address\x18\x03 \x01(\tR\rsignerAddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12!\n" +
	"\fvoting_power\x18\x05 \x01(\x04R\vvotingPower\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12!\n" +
	"\fmetadata_uri\x18\a \x01(\tR\vmetadataUri\"\xf0\x04\n" +
	"\n" +
	"RiskReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x14\n" +
	"\x05denom\x18\x05 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12,\n" +
	"\x12source_response_id\x18\b \x01(\tR\x10sourceResponseId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\t \x01(\rR\triskScore\x12'\n" +
	"\x0frisk_categories\x18\n" +
	" \x03(\tR\x0eriskCategories\x12#\n" +
	"\rexposure_type\x18\v \x01(\tR\fexposureType\x12'\n" +
	"\x0fobserved_height\x18\f \x01(\x04R\x0eobservedHeight\x12#\n" +
	"\rexpiry_height\x18\r \x01(\x04R\fexpiryHeight\x12%\n" +
	"\x0epolicy_version\x18\x0e \x01(\tR\rpolicyVersion\x12#\n" +
	"\revidence_hash\x18\x0f \x01(\fR\fevidenceHash\x12,\n" +
	"\x12llm_rationale_hash\x18\x10 \x01(\fR\x10llmRationaleHash\x12\x1c\n" +
	"\tsubmitter\x18\x11 \x01(\tR\tsubmitter\x12/\n" +
	"\x13submitter_signature\x18\x12 \x01(\fR\x12submitterSignature\"\x91\x04\n" +
	"\fSanctionCase\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x12@\n" +
	"\vtarget_type\x18\x04 \x01(\x0e2\x1f.sanction.v1.SanctionTargetTypeR\n" +
	"targetType\x12F\n" +
	"\x10requested_action\x18\x05 \x01(\x0e2\x1b.sanction.v1.SanctionActionR\x0frequestedAction\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.sanction.v1.CaseStatusR\x06status\x12\x1d\n" +
	"\n" +
	"report_ids\x18\a \x03(\tR\treportIds\x12#\n" +
	"\ropened_height\x18\b \x01(\x04R\fopenedHeight\x124\n" +
	"\x16voting_deadline_height\x18\t \x01(\x04R\x14votingDeadlineHeight\x12'\n" +
	"\x0fexecuted_height\x18\n" +
	" \x01(\x04R\x0eexecutedHeight\x12%\n" +
	"\x0epolicy_version\x18\v \x01(\tR\rpolicyVersion\x12#\n" +
	"\rdecision_hash\x18\f \x01(\fR\fdecisionHash\"\xc4\x02\n" +
	"\fSanctionVote\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12/\n" +
	"\x06option\x18\x03 \x01(\x0e2\x17.sanction.v1.VoteOptionR\x06option\x12D\n" +
	"\x0fapproved_action\x18\x04 \x01(\x0e2\x1b.sanction.v1.SanctionActionR\x0eapprovedAction\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0erationale_hash\x18\x06 \x01(\fR\rrationaleHash\x12#\n" +
	"\rsigned_height\x18\a \x01(\x04R\fsignedHeight\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xc9\x01\n" +
	"\x0eActiveSanction\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x123\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1b.sanction.v1.SanctionActionR\x06action\x12)\n" +
	"\x10activated_height\x18\x05 \x01(\x04R\x0factivatedHeight\"f\n" +
	"\fFreezeRecord\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12#\n" +
	"\rfrozen_height\x18\x03 \x01(\x04R\ffrozenHeight\"\xd8\x02\n" +
	"\x0fExecutionRecord\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x123\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1b.sanction.v1.SanctionActionR\x06action\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\fR\x06txHash\x12%\n" +
	"\x0etarget_address\x18\x04 \x01(\tR\rtargetAddress\x12\x1a\n" +
	"\bexecutor\x18\x05 \x01(\tR\bexecutor\x12'\n" +
	"\x0fexecuted_height\x18\x06 \x01(\x04R\x0eexecutedHeight\x12\x1f\n" +
	"\vresult_code\x18\a \x01(\tR\n" +
	"resultCode\x12%\n" +
	"\x0eresult_message\x18\b \x01(\tR\rresultMessage\x12*\n" +
	"\x11state_change_hash\x18\t \x01(\fR\x0fstateChangeHash*y\n" +
	"\x12SanctionTargetType\x12$\n" +
	" SANCTION_TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SANCTION_TARGET_TYPE_TX\x10\x01\x12 \n" +
	"\x1cSANCTION_TARGET_TYPE_ADDRESS\x10\x02*\xd5\x01\n" +
	"\x0eSanctionAction\x12\x1f\n" +
	"\x1bSANCTION_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SANCTION_ACTION_WATCH\x10\x01\x12\x1c\n" +
	"\x18SANCTION_ACTION_BLOCK_TX\x10\x02\x12\"\n" +
	"\x1eSANCTION_ACTION_FREEZE_ADDRESS\x10\x03\x12 \n" +
	"\x1cSANCTION_ACTION_ESCROW_FUNDS\x10\x04\x12#\n" +
	"\x1fSANCTION_ACTION_REVERT_TRANSFER\x10\x05*\xc2\x01\n" +
	"\n" +
	"CaseStatus\x12\x1b\n" +
	"\x17CASE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CASE_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14CASE_STATUS_APPROVED\x10\x02\x12\x18\n" +
	"\x14CASE_STATUS_REJECTED\x10\x03\x12\x18\n" +
	"\x14CASE_STATUS_EXECUTED\x10\x04\x12\x17\n" +
	"\x13CASE_STATUS_EXPIRED\x10\x05\x12\x17\n" +
	"\x13CASE_STATUS_REVOKED\x10\x06*s\n" +
	"\n" +
	"VoteOption\x12\x1b\n" +
	"\x17VOTE_OPTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13VOTE_OPTION_APPROVE\x10\x01\x12\x16\n" +
	"\x12VOTE_OPTION_REJECT\x10\x02\x12\x17\n" +
	"\x13VOTE_OPTION_ABSTAIN\x10\x03B5Z3github.com/crossref/crossref-chain/x/sanction/typesb\x06proto3"

var (
	file_sanction_v1_types_proto_rawDescOnce sync.Once
	file_sanction_v1_types_proto_rawDescData []byte
)

func file_sanction_v1_types_proto_rawDescGZIP() []byte {
	file_sanction_v1_types_proto_rawDescOnce.Do(func() {
		file_sanction_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sanction_v1_types_proto_rawDesc), len(file_sanction_v1_types_proto_rawDesc)))
	})
	return file_sanction_v1_types_proto_rawDescData
}

var file_sanction_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sanction_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sanction_v1_types_proto_goTypes = []any{
	(SanctionTargetType)(0), // 0: sanction.v1.SanctionTargetType
	(SanctionAction)(0),     // 1: sanction.v1.SanctionAction
	(CaseStatus)(0),         // 2: sanction.v1.CaseStatus
	(VoteOption)(0),         // 3: sanction.v1.VoteOption
	(*AgentInfo)(nil),       // 4: sanction.v1.AgentInfo
	(*RiskReport)(nil),      // 5: sanction.v1.RiskReport
	(*SanctionCase)(nil),    // 6: sanction.v1.SanctionCase
	(*SanctionVote)(nil),    // 7: sanction.v1.SanctionVote
	(*ActiveSanction)(nil),  // 8: sanction.v1.ActiveSanction
	(*FreezeRecord)(nil),    // 9: sanction.v1.FreezeRecord
	(*ExecutionRecord)(nil), // 10: sanction.v1.ExecutionRecord
}
var file_sanction_v1_types_proto_depIdxs = []int32{
	0, // 0: sanction.v1.SanctionCase.target_type:type_name -> sanction.v1.SanctionTargetType
	1, // 1: sanction.v1.SanctionCase.requested_action:type_name -> sanction.v1.SanctionAction
	2, // 2: sanction.v1.SanctionCase.status:type_name -> sanction.v1.CaseStatus
	3, // 3: sanction.v1.SanctionVote.option:type_name -> sanction.v1.VoteOption
	1, // 4: sanction.v1.SanctionVote.approved_action:type_name -> sanction.v1.SanctionAction
	1, // 5: sanction.v1.ActiveSanction.action:type_name -> sanction.v1.SanctionAction
	1, // 6: sanction.v1.ExecutionRecord.action:type_name -> sanction.v1.SanctionAction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sanction_v1_types_proto_init() }
func file_sanction_v1_types_proto_init() {
	if File_sanction_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sanction_v1_types_proto_rawDesc), len(file_sanction_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sanction_v1_types_proto_goTypes,
		DependencyIndexes: file_sanction_v1_types_proto_depIdxs,
		EnumInfos:         file_sanction_v1_types_proto_enumTypes,
		MessageInfos:      file_sanction_v1_types_proto_msgTypes,
	}.Build()
	File_sanction_v1_types_proto = out.File
	file_sanction_v1_types_proto_goTypes = nil
	file_sanction_v1_types_proto_depIdxs = nil
}
